### PR TITLE
Slowdelete.js Pull request. 

### PR DESCRIPTION
**Pull request by Abe-Telo**
I hope this is the way to do a pull request. Please double check

### CODE REVIEW

**Review by BrokenDesign — CHANGES_REQUESTED** [review]
What are the hard coded channel references to '690071308586844243'. Please can you also correct spelling.

**Review by Abe-Telo — COMMENTED** [review]
Hard coded file in slowdelete.js is resolved. owner.js was deleted.

**Review by Abe-Telo — COMMENTED** [review]
ok your request was reviewed. Msg.js is the only file i didn't bother looking yet as its still being worked on.

**Review by Abe-Telo — COMMENTED** [review]
something small removed header require permission.js from irc.js

**Pull request merged**
